### ISSUE TITLE
Track missing in results table 

### ISSUE THREAD

**Issue by Macacosky** [Re-Volt-America/RVA#101]
The track "Władysławowo" doesn't have a short name to spread in the results table.
https://rva.lat/sessions/664560a68a6ce3d027c38424
After Sakura just appears a "?".

**Comment by BGMP** [comment]
@EstebanMz Might be an issue with RVA-Data

**Comment by EstebanMz** [comment]
Seems that it's that special 'ł' character in its name. I replaced it with a regular L because the font used for titles in the website doesn't support 'ł', should I fix its name anyways?

**Comment by EstebanMz** [comment]
[Updated RVA-Data](https://github.com/Re-Volt-America/RVA-Data/commit/e3956eea64db1c750d8ec09b1cc0dc392651ce9a) (and track edited in the web just in case) with the "polish" L.
