### ISSUE TITLE
The participation multiplier is not working in the Leaderboards.

### ISSUE THREAD

**Issue by Macacosky** [Re-Volt-America/RVA#102]
We have played 2 sessions, 40 races in total and for some players this parameter is 0.5, even when some players played the entire number of races.
https://rva.lat/rankings/664413ae8a6ce38942c9d9a6?locale=en

**Comment by BGMP** [comment]
I'll take a look at this whenevr I can. I know there's an underlying problem with how we're storing the stats to the database.

**Comment by BGMP** [comment]
Fixedb by https://github.com/Re-Volt-America/RVA/commit/824273f37122e4340c251be54e4ea8a9971c8165
