### ISSUE TITLE
Another track missing in the results table

### ISSUE THREAD

**Issue by Yunnnnnnnnnn** [Re-Volt-America/RVA#104]
"HMS: Invincible" appears as "?" in the results table.

Attached session with the bug:
https://rva.lat/sessions/664803228a6ce3d027c38600

Appears between Game Room 2 (GR2) and Toy World 2 (TW2).
![image](https://github.com/Re-Volt-America/RVA/assets/68486176/528715d4-232c-47a5-a4b9-ccdac0b68f82)

**Comment by EstebanMz** [comment]
Thanks for the report, it's been fixed now.
