### ISSUE TITLE
"Download as PNG" does not work on the weekly schedule

### ISSUE THREAD

**Issue by Yunnnnnnnnnn** [Re-Volt-America/RVA#105]
Over at the weekly schedule page, there's an option to download the schedule of the day as a PNG.
This button does not work. There's a similar button over at the results table to download as a PNG and it does work.

This happens currently on the [weekly schedule](https://rva.lat/weekly_schedules/66413c2e8a6ce35c64c985aa) of the 13th to the 19th of May.

![image](https://github.com/Re-Volt-America/RVA/assets/68486176/48da780b-42bf-4979-b931-b34cb1da8fd4)

**Comment by BGMP** [comment]
Relates to https://github.com/Re-Volt-America/RVA/pull/99

**Comment by BGMP** [comment]
Resolved by https://github.com/Re-Volt-America/RVA/commit/f0c7219517253782253b4d353aab4dbf326b5f81
