### ISSUE TITLE
Uploading a session log redirects to the results table

### ISSUE THREAD

**Issue by Yunnnnnnnnnn** [Re-Volt-America/RVA#107]
* This is a suggestion.

I think it would be nice for organizers/hosts to get redirected to the uploaded session's result table.
Beats having to navigate through the menus and also makes it so posting results is a quicker process overall.
It is also the way [Re-Volt I/O results](https://online.re-volt.io/sessions/results.php) are done.

Examples:
![image](https://github.com/Re-Volt-America/RVA/assets/68486176/7db3f639-f70e-40aa-871c-e5f77f97504b)
![image](https://github.com/Re-Volt-America/RVA/assets/68486176/0d22e148-6278-4582-a811-c7f247181d35)

**Comment by BGMP** [comment]
Update: This is a thing only in production environments. We must look into it as it has intermittent behaviour; sometimes you are redirected, and some other times you are not

**Comment by BGMP** [comment]
@nickskyline any chance you can take a look at this? If not I'll reassign it to myself

**Comment by nickskyline** [comment]
@BGMP No, I can't at this moment, apologies

**Comment by BGMP** [comment]
Resolved by https://github.com/Re-Volt-America/RVA/commit/11a392b6db3d12ee418fe69022eec20b4c98d971
