### ISSUE TITLE
Shortcut typo

### ISSUE THREAD

**Issue by Nickurn** [Re-Volt-America/RVA#108]
Yo! Today at the morning I was looking at recent RVA session results and spotted a typo shortcut, instead of PP it's PA twice.
![easdf](https://github.com/Re-Volt-America/RVA/assets/113555362/31a73c47-cefa-4293-b035-e14ed9e72679)

**Comment by nickskyline** [comment]
Thank you for reporting!

Resolved by https://github.com/Re-Volt-America/RVA/commit/6179db0072d82c77bd49c4a926e37ad84f833cb6
