### ISSUE TITLE
Translation mission on Spanish (Spain flag)

### ISSUE THREAD

**Issue by Macacosky** [Re-Volt-America/RVA#109]
On the "Clasificación de Coches" subtopic the text should be in Spanish.
https://rva.lat/points

**Comment by BGMP** [comment]
Translated on https://crowdin.com/editor/rva/96/enus-es?view=comfortable&filter=basic&value=0#q=In%20Re-Volt%20America,%20cars%20are%20assigned%20a%20'multiplier'%20depending%20on%20their%20top%20speed,%20acceleration,%20weight,%20and%20other%20characteristi
