### ISSUE TITLE
Tracks not being recognized in the results table

### ISSUE THREAD

**Issue by Yunnnnnnnnnn** [Re-Volt-America/RVA#110]
Some tracks are not recognized in the table, such as Hull Breach 3K and Kadish Sprint not having their shortened names and linking to the wrong tracks.
The issue is prevalent [here](https://rva.lat/sessions/66528e828a6ce35e3b327b84)

Example:
![image](https://github.com/Re-Volt-America/RVA/assets/68486176/7f75c1e5-f61c-4ec0-9f96-68a1b293a660)

GIF Example (notice the links in bottom right):
![floorp_pzRdlzXGrJ](https://github.com/Re-Volt-America/RVA/assets/68486176/5a20c829-97d0-42f8-8b4d-3f5940c28e78)

**Comment by Yunnnnnnnnnn** [comment]
Quick note: This also has been plaguing other sessions but it hasn't been noticed apparently.

It also happened on the [11th Session of the 1st ranking](https://rva.lat/sessions/66513cc08a6ce35e3b327ab4) with the same issues as the one opened in the issue, and another case was easily missed on the [10th Session of the 1st ranking](https://rva.lat/sessions/664fecb18a6ce35e3b3279dc) with "Ghost Town 2" being marked as Stadvolt (SVT).
Seems like it's not a one-time occurrence.

Example for the 10th session:
![image](https://github.com/Re-Volt-America/RVA/assets/68486176/b0ff477d-70d8-4896-9b28-90acec327428)

**Comment by BGMP** [comment]
@EstebanMz Maybe it's a problem with RVA-Data? Would you mind taking a look?

If it's not, then ping me back and I'll take a look at the backend whenever I can

**Comment by EstebanMz** [comment]
@BGMP I couldn't find anything wrong within the database; either a typo, a pattern that leads to that error... nothing.

**Comment by BGMP** [comment]
> @BGMP I couldn't find anything wrong within the database; either a typo, a pattern that leads to that error... nothing.

@EstebanMz alright, thank you. I'll try to take a look
