### ISSUE TITLE
Wladyslawowo is showing up twice on the tracklist generator and on the list of tracks

### ISSUE THREAD

**Issue by EstebanMz** [Re-Volt-America/RVA#115]
[This commit](https://github.com/Re-Volt-America/RVA-Data/commit/469a1a4110c3334dc3cc32d5520a6cf7edefe20f) seems that it created a duplicate of the track instead of just rename it. 
In the most [recent tracklist](https://rva.lat/weekly_schedules/665dfb3f8a6ce337eb010396) generated, the track shows up twice (from monday to thursday) and you can confirm and also on the last page of the track list it appears twice.
![imagen](https://github.com/Re-Volt-America/RVA/assets/19150477/f10889db-bc01-4e50-8f87-b8d8d849c189)

**Comment by BGMP** [comment]
@EstebanMz I think this issue was resolved at some point. I don't see the duplicate track on the tracks page anymore. Would you mind corroborating it, please?

**Comment by EstebanMz** [comment]
Yeah, Nick implemented an option to delete tracks through edit mode, and I just noticed it like last week.

**Comment by BGMP** [comment]
Nice!
