### ISSUE TITLE
Add the option to Delete Cars individually

### ISSUE THREAD

**Issue by EstebanMz** [Re-Volt-America/RVA#122]
After the recent pack updates that added new cars and deleted the same amount, the old cars remained in the cars tabs (the new cars were added successfully).
This issue had already happened for the tracks and it was solved by adding a "Delete Track" button that let the admins delete a track individually.

**Comment by nickskyline** [comment]
Resolved by https://github.com/Re-Volt-America/RVA/commit/025e2a136635695f3f81afc4a64424caa29e8aca

Check if it works well :shipit:

**Comment by EstebanMz** [comment]
The changes only get effective after I import again the CSV file, without doing that, when you click a car that was deleted you'll get a 404 error. I'd mark this as solved, but if you want to keep checking what's wrong, then go ahead.
![2024-08-09 14_40_59-Re-Volt America - Amateur Cars — Mozilla Firefox](https://github.com/user-attachments/assets/05dd5390-b37b-438c-8364-757d2527af18)

**Comment by BGMP** [comment]
@EstebanMz Don't mark things as resolved if they are not, please.

@nickskyline Could you double check on what Esteban said?

Thank you both 🙏

**Comment by nickskyline** [comment]
@EstebanMz It is a problem related to the cache, now check if you still get the same error. https://github.com/Re-Volt-America/RVA/commit/08c56222ec71d776fa10d70e4703c0f9c707ffbc

**Comment by EstebanMz** [comment]
Now it's working as intended, thank you for adding this function this fast.
-# Blue Label
