### ISSUE TITLE
Edit and destroy options are visible even without being logged.

### ISSUE THREAD

**Issue by nickskyline** [Re-Volt-America/RVA#25]
![image](https://github.com/Re-Volt-America/RVA/assets/137591602/5dfb3e0a-9e0f-4680-9df2-207d06aa60f0)

**Comment by BGMP** [comment]
Well, the action validations are present. That is to say, you *can* see those buttons, but not actually use them as a non-staff user. I'll just mark this as resolved because it isn't an issue in and of itself.
