### ISSUE TITLE
Bookmark icons are now broken

### ISSUE THREAD

**Issue by Yunnnnnnnnnn** [Re-Volt-America/RVA#50]
Since the website got a revamp, the bookmarks have lost their icons.
Example in the screenshot below.

![Qy5cbKX5tL](https://github.com/Re-Volt-America/RVA/assets/68486176/2119ad53-2fd2-43a6-9f4f-59718e13379c)

**Comment by BGMP** [comment]
This fixed itself after recompiling all assets in production
