### ISSUE TITLE
Add a way to see RVA events on the RVGL launcher?

### ISSUE THREAD

**Issue by Santiii733** [Re-Volt-America/RVA#57]
Maybe it's good idea to add that cause for attract more players

**Comment by BGMP** [comment]
Not website-related, but I could look into this. It'd take someone to manually update these events every week for how it's currently set up for the launcher though 😬

**Comment by Santiii733** [comment]
> Not website-related, but I could look into this. It'd take someone to manually update these events every week for how it's currently set up for the launcher though 😬

Can be work that 🤔

**Comment by BGMP** [comment]
> > Not website-related, but I could look into this. It'd take someone to manually update these events every week for how it's currently set up for the launcher though 😬
> 
> Can be work that 🤔

do you want to do it?

**Comment by Santiii733** [comment]
> > > Not website-related, but I could look into this. It'd take someone to manually update these events every week for how it's currently set up for the launcher though 😬
> > 
> > 
> > Can be work that 🤔
> 
> do you want to do it?

Yes sure! Can do that from here :P

**Comment by Santiii733** [comment]
Updated comment

**Comment by BGMP** [comment]
Feel free to re-open this issue if you want us to do anything on the website regarding events. For now, this feels like an RVGL Launcher related issue. Maybe open an issue here instead? https://gitlab.com/re-volt/rvgl-launcher/-/issues

Thanks for the suggestion!

**Comment by Santiii733** [comment]
> Feel free to re-open this issue if you want us to do anything on the website regarding events. For now, this feels like an RVGL Launcher related issue. Maybe open an issue here instead? https://gitlab.com/re-volt/rvgl-launcher/-/issues
> 
> Thanks for the suggestion!

https://gitlab.com/re-volt/rvgl-launcher/-/issues/21
