### ISSUE TITLE
Missing characters in NissanOpti

### ISSUE THREAD

**Issue by BGMP** [Re-Volt-America/RVA#74]
The "¿" character doesn't exist in the NissanOpti font... this will cause problems like the following:

![Capture](https://github.com/Re-Volt-America/RVA/assets/26081543/ed06fffe-a925-4664-a36c-c1316ef72be2)

Likewise, "¡" doesn't exist either:

![Capteure](https://github.com/Re-Volt-America/RVA/assets/26081543/854701a3-5c1c-4c77-8ba1-f3c3443e8458)

I guess I'll have to fire up FontForge and try to add them into the font pack. Not sure when I'll be able to, though

**Comment by Y100XTT** [comment]
Here's a font file with the missing glyphs 
[NissanOpti-rva.zip](https://github.com/Re-Volt-America/RVA/files/14898345/NissanOpti-rva.zip)

**Comment by Y100XTT** [comment]
I forgot to upload NissanOpti-Italic alongside the normal font.
[NissanOpti-Italic-rva.zip](https://github.com/Re-Volt-America/RVA/files/14898474/NissanOpti-Italic-rva.zip)
