### ISSUE TITLE
Import cars feature isn't sorting the content following the input file

### ISSUE THREAD

**Issue by EstebanMz** [Re-Volt-America/RVA#92]
After making use of this tool to [update the multipliers for a bunch of cars](https://github.com/Re-Volt-America/RVA-Data/commit/3498f152fb22335691a9a66d43f0b77828e00705), the list of cars keeps the same order as before instead of following given by the CSV file itself.
![2024-05-13 10_54_01-Re-Volt America - Autos Pro — Mozilla Firefox](https://github.com/Re-Volt-America/RVA/assets/19150477/97c6bdcb-0eeb-4eba-90c4-fe93c0f1c83b)
![2024-05-13 10_55_59-GitHub Desktop](https://github.com/Re-Volt-America/RVA/assets/19150477/60875bd8-393d-4d36-862e-bbd1a36658fb)

**Comment by BGMP** [comment]
Resolved by https://github.com/Re-Volt-America/RVA/commit/b1263a113ab8499ba647842994bbc525c2661ad5

**Comment by EstebanMz** [comment]
For some reason the fix isn't working properly, actually the cars whose multiplier has been recently updated (pink number) are either at the start or at the end of their respective multiplier group. I've numbered every car in the screenshot with what should be their right sort order.
![imagen](https://github.com/Re-Volt-America/RVA/assets/19150477/4c919062-6dc8-4aba-a28c-45f70676af4a)

**Comment by nickskyline** [comment]
Resolved by [1d7ec7a](https://github.com/Re-Volt-America/RVA/commit/1d7ec7a56548a547053037d5904ed5591970d14d)
