### ISSUE TITLE
Add author's field in car model 

### ISSUE THREAD

**Issue by nickskyline** [Re-Volt-America/RVA#94]
When importing them, an error occurs when trying to determine if it is stock or not because the new datasets contain that extra column. https://github.com/Re-Volt-America/RVA-Data/issues/13

![image](https://github.com/Re-Volt-America/RVA/assets/137591602/58d2c9ab-4e19-4b76-a4c9-db3e65a7b818)

In the same way, we have to modify the views in order to display all this information.

Edit: Author's field is actually done for tracks.

**Comment by BGMP** [comment]
Can you take care of this @nickskyline ? If not then let me know, please

**Comment by BGMP** [comment]
Resolved by https://github.com/Re-Volt-America/RVA/commit/b1263a113ab8499ba647842994bbc525c2661ad5
